# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heat', models.IntegerField(default=0)),
                ('date', models.DateTimeField(verbose_name='date')),
            ],
        ),
    ]
