# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='date',
            field=models.DateTimeField(verbose_name='temperature data'),
        ),
    ]
