# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 21:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0003_auto_20151214_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 14, 21, 23, 45, 39878), verbose_name='temp date'),
        ),
    ]
